return {
	ac_01_02_tom0000 = {
		text = "%CHoly shit, stop playin' around and stick to the prep work.",
		left = 960,
		top = 50,
		skippable = true,
	},
	ac_04_10_hit0000 = {
		text = "%CWe will lose this war. However, do not fear!",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_04_10_hit0001 = {
		text = "%CIn the distant future, mankind will reach an inevitable metamorphosis,\nand humanity as we know it will cease to exist!",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_04_10_cma0000 = {
		text = "%CPresident Kennedy... has been shot.",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_04_10_arm0000 = {
		text = "%CThat's... one small step for man, one giant leap for mankind.",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_04_10_cwa0000 = {
		text = "%CAs part of the ceremony to mark the remarbling of the Arecibo telescope,\na radio message was broadcast into space.",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_04_10_occ0000 = {
		text = "%CNostradamus said that the Great King of Terror will arrive!\nThe world ends in 1999, this is nothing but the truth!",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_04_10_cmb0000 = {
		text = "%CBreaking News: Lehman Brothers has declared bankruptcy. I repeat...",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_04_10_cwb0000 = {
		text = "%CLook at this crowd! People have gathered from all over the world to witness\nthe completion of the Sagrada Família.",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_04_10_eng0000 = {
		text = "%CDue to recent circumstances... we have decided to cease\ndevelopment of the Earth Simulator GAIA.",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_04_10_rom0000 = {
		text = "%CI've been in line since two nights ago! Man, I just have to get a carrianode for myself!",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_04_10_cwc0000 = {
		text = "%CMany believe that the SA4D have gone haywire, but the details are unclear.",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_04_10_cwc0001 = {
		text = "%CShinjuku, Akasaka, and Ochanomizu have been affected,\nbut there are reports of other areas sustaining major damage.",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_load_pol0000 = {
		text = "Buzz off.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0001 = {
		text = "Quit it already.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0002 = {
		text = "Just watch me.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0003 = {
		text = "Let me focus.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0004 = {
		text = "Hey, enough of that!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0005 = {
		text = "Don't interfere.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0006 = {
		text = "Mind your own business.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0007 = {
		text = "Why?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0008 = {
		text = "Nope.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0009 = {
		text = "Not doing it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0010 = {
		text = "Don't need it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0011 = {
		text = "Right now? Hrm...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0012 = {
		text = "Not happening.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0013 = {
		text = "Go away.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0014 = {
		text = "You're being a pain.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0015 = {
		text = "I know, I know.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0016 = {
		text = "This is what you meant, right?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0017 = {
		text = "Quit it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0018 = {
		text = "Please refrain from that, if you could.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0019 = {
		text = "We're in the middle of something here.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0020 = {
		text = "I'm talking right now.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0021 = {
		text = "Well, that screwed things up.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0022 = {
		text = "All right, that wasn't bad.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0023 = {
		text = "Not... right now...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0024 = {
		text = "This isn't the right time.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0025 = {
		text = "Stop that for a sec.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0026 = {
		text = "No no no no...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0027 = {
		text = "Just quit it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0028 = {
		text = "Yeah, yeah, whatever.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0029 = {
		text = "Shut it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0030 = {
		text = "Nah.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0031 = {
		text = "Can't agree with that.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0032 = {
		text = "I don't get it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0033 = {
		text = "Wait. I'm not giving up.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0034 = {
		text = "Don't bother me!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0035 = {
		text = "Wait...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0036 = {
		text = "Shh...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0037 = {
		text = "We failed...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0038 = {
		text = "It's over...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0039 = {
		text = "I'm... alive?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0040 = {
		text = "No. Not yet.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0041 = {
		text = "Let me keep at it for now!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0042 = {
		text = "We can still do this.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0043 = {
		text = "No. I'm gonna keep going.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0044 = {
		text = "Not now.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0045 = {
		text = "I'm focusing. Pipe down.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0046 = {
		text = "Let me concentrate.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0047 = {
		text = "Quit worrying.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0048 = {
		text = "C'mon, it's all good now.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0049 = {
		text = "What's going on?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0050 = {
		text = "We just got back...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0051 = {
		text = "No...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0052 = {
		text = "Not now!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0053 = {
		text = "Shit!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0054 = {
		text = "Let me focus...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0055 = {
		text = "Hey, quiet.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0056 = {
		text = "Let me listen.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0057 = {
		text = "We're not doing it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0058 = {
		text = "We don't need it now.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0059 = {
		text = "I don't think we need it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0060 = {
		text = "Don't just bring it up like that.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0061 = {
		text = "Not gonna do it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0062 = {
		text = "Nuh uh.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0063 = {
		text = "No, thank you.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0064 = {
		text = "I won't.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0065 = {
		text = "Yeah, no. Bye-bye.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0066 = {
		text = "Go away.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0067 = {
		text = "I'm good, thanks.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0068 = {
		text = "Just watch.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0069 = {
		text = "Hey, chill.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0070 = {
		text = "Help me out, will ya?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0071 = {
		text = "I'm trying to focus right now.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0072 = {
		text = "Right now?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0073 = {
		text = "I don't think we have to.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0074 = {
		text = "Leave me alone.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0075 = {
		text = "Don't complain.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0076 = {
		text = "You bored? Deal with it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0077 = {
		text = "Later.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0078 = {
		text = "Not now.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0079 = {
		text = "Why?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0080 = {
		text = "No, we're good.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0081 = {
		text = "What do you want me to do?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0082 = {
		text = "Are you just bothering me?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0083 = {
		text = "Huhhh? Nowww?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0084 = {
		text = "Can't agree to that.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0085 = {
		text = "I'll think about it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0086 = {
		text = "Hmm?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0087 = {
		text = "We gotta find out what this is about!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0088 = {
		text = "Hm?!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0089 = {
		text = "Wait. Let's see where this goes.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0090 = {
		text = "Yeah. I don't like this either.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0091 = {
		text = "Oof, what the hell, man?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0092 = {
		text = "Hey, no worries.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0093 = {
		text = "Not! Nowwww!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0094 = {
		text = "S-Stop picking on me...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0095 = {
		text = "Yeah, this is freaky.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0096 = {
		text = "Shit, dunno why I'm sweating...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0097 = {
		text = "No. It's too early.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0098 = {
		text = "Yeah. Wait for the right moment.",
		left = 420,
		top = 32
	},
	ac_load_pol0099 = {
		text = "Feeling anxious, huh?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0100 = {
		text = "I know, this is bad shit.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0101 = {
		text = "Yeah! We'll need it soon.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0102 = {
		text = "Now's... the time?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0103 = {
		text = "Are you scared too?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0104 = {
		text = "Lemme focus for a sec.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0105 = {
		text = "Too early.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0106 = {
		text = "No!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0107 = {
		text = "Gotta figure 'im out.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0108 = {
		text = "Where is he?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0109 = {
		text = "Calm down, calm down...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0110 = {
		text = "Don't... worry...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0111 = {
		text = "I can still... do this...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0112 = {
		text = "We're good now.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0113 = {
		text = "Yeah. We can't relax just yet.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0114 = {
		text = "I did pretty good, yeah?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0115 = {
		text = "What...?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0116 = {
		text = "Already? C'mon!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0117 = {
		text = "What... happened?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0118 = {
		text = "I gotta know what's going on first...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0119 = {
		text = "But... what if I faint again?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0120 = {
		text = "Hey, things are chill now.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0121 = {
		text = "No need for that.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0122 = {
		text = "Come on, now's not the time.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0123 = {
		text = "I wanna kick back for a bit.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0124 = {
		text = "You want my attention that bad?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0125 = {
		text = "You got nothing better to do, huh?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0126 = {
		text = "Are you... playing with that?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0127 = {
		text = "I'm closing it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0128 = {
		text = "Get off my ass.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0129 = {
		text = "Huh? Why?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0130 = {
		text = "Hwuh?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0131 = {
		text = "*yawn*",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0132 = {
		text = "It's fine.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0133 = {
		text = "You should listen too.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0134 = {
		text = "Let's focus on her story.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0135 = {
		text = "Holy shit...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0136 = {
		text = "Oz has gone through hell...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0137 = {
		text = "Hey... Quit it!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0138 = {
		text = "I've been framed...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0139 = {
		text = "Nnghh...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0140 = {
		text = "Nghh. I'm feeling nervous.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0141 = {
		text = "Phew...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0142 = {
		text = "Oh, I'm so glad...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0143 = {
		text = "Let's enjoy the show.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0144 = {
		text = "We did what we could.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0145 = {
		text = "Why? It went well, yeah?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0146 = {
		text = "You get some rest too.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0147 = {
		text = "Ohhh shit, you jelly?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0148 = {
		text = "G-Good thinking!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0149 = {
		text = "We're still good.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0150 = {
		text = "Huh?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0151 = {
		text = "No thanks.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0152 = {
		text = "Here we go.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0153 = {
		text = "Damn that JUNO!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0154 = {
		text = "Fuuuck...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0155 = {
		text = "I get you, but...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0156 = {
		text = "Giving up already?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0157 = {
		text = "I wanna think about it some more.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0158 = {
		text = "Let's think this through first.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0159 = {
		text = "I know. Shit's getting real.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0160 = {
		text = "Yeah. This isn't good...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0161 = {
		text = "I'll think about it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0162 = {
		text = "Don't rush it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0163 = {
		text = "I'll use it when the time comes.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0164 = {
		text = "Is that really gonna do it?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0165 = {
		text = "I don't think so.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0166 = {
		text = "Later. Maybe.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0167 = {
		text = "Don't distract me.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0168 = {
		text = "I'm figuring this out.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0169 = {
		text = "Hmm...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0170 = {
		text = "It's hard to say.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0171 = {
		text = "No...!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0172 = {
		text = "I'm fine...!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0173 = {
		text = "Not yet...!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0174 = {
		text = "NNGHNNGH...!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0175 = {
		text = "Gotta... breathe!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0176 = {
		text = "Hahhh, hahhh... Shit!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0177 = {
		text = "I got a bad feeling about this too.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0178 = {
		text = "I might have to use it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0179 = {
		text = "Holy... fucking... shit.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0180 = {
		text = "I know!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0181 = {
		text = "Hang... on!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0182 = {
		text = "Th-That's not the point...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0183 = {
		text = "What's going on...?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0184 = {
		text = "Is this for real?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0185 = {
		text = "Seriously...?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0186 = {
		text = "Shit, shit, shit!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0187 = {
		text = "W-Wait!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0188 = {
		text = "I-I'll do what I can first!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0189 = {
		text = "C'mon. Just watch.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0190 = {
		text = "Trust me a little.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0191 = {
		text = "Don't worry. It's all good.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0192 = {
		text = "Yo, calm down.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0193 = {
		text = "Gonna charge right through this.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0194 = {
		text = "Are you doing this at random?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0195 = {
		text = "No. It's fine.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0196 = {
		text = "Hard pass.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0197 = {
		text = "Well...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0198 = {
		text = "I can't decide...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0199 = {
		text = "I'll use it if I have to.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0200 = {
		text = "You're making me worried.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0201 = {
		text = "I-It ended well, yeah?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0202 = {
		text = "Hah. What's up?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0203 = {
		text = "Oh, am I glad to see this screen.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0204 = {
		text = "We did good this time too.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0205 = {
		text = "C'mon, we're done.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0206 = {
		text = "You're interested too, aren't you?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0207 = {
		text = "Let's hear him out.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0208 = {
		text = "We're doing great, aren't we?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0209 = {
		text = "This is no time to dwell on the past.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0210 = {
		text = "Not gonna lie, I'm debating.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0211 = {
		text = "I think... I can wait.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0212 = {
		text = "I might need to.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0213 = {
		text = "Gotta find the right time.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0214 = {
		text = "We'll use it when it counts.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0215 = {
		text = "Let's be careful.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0216 = {
		text = "Not right now.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0217 = {
		text = "The situation's not good.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0218 = {
		text = "Yeah. Might have to use it soon.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0219 = {
		text = "Calm down.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0220 = {
		text = "Don't rush me.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0221 = {
		text = "Don't scare me like that.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0222 = {
		text = "I might need it again.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0223 = {
		text = "Yeah, I'm keeping my guard up.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0224 = {
		text = "Kh...!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0225 = {
		text = "I know!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0226 = {
		text = "Why'd it end up like this?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0227 = {
		text = "I'll get it right this time!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0228 = {
		text = "What was that...?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0229 = {
		text = "Wait.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0230 = {
		text = "I'm thinking...!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0231 = {
		text = "Ngh...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0232 = {
		text = "Not... now...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0233 = {
		text = "Hah, hahhh...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0234 = {
		text = "Don't worry.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0235 = {
		text = "Leave it to me.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0236 = {
		text = "Why... is this happening...?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0237 = {
		text = "I can't...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0238 = {
		text = "I don't feel up to it...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0239 = {
		text = "No...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0240 = {
		text = "If that happens again...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0241 = {
		text = "There's no way.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0242 = {
		text = "Nothing's gonna work.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0243 = {
		text = "Stop...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0244 = {
		text = "Honestly, I'm still not sure about this.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0245 = {
		text = "I'll use it if I need to.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0246 = {
		text = "If I had a choice, I'd rather not use it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0247 = {
		text = "We're still fine.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0248 = {
		text = "This isn't it... I think.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0249 = {
		text = "Yeah. We can't relax just yet.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0250 = {
		text = "How's that fucking possible?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0251 = {
		text = "No...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0252 = {
		text = "Let me focus.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0253 = {
		text = "I want you to watch me.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0254 = {
		text = "Now we just see what happens.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0255 = {
		text = "Let's hope it works out.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0256 = {
		text = "You saw it too, huh?!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0257 = {
		text = "Hahah! We actually did it!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0258 = {
		text = "Don't give me that...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0259 = {
		text = "Shit's not gonna work.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0260 = {
		text = "Hm?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0261 = {
		text = "What are you trying to tell me?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0262 = {
		text = "You know I can't, right?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0263 = {
		text = "Watch over us, will ya?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0264 = {
		text = "Keep your fingers crossed, aight?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0265 = {
		text = "I'm sure we'll make it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0266 = {
		text = "Don't put pressure on me.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0267 = {
		text = "I'll do what I can.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0268 = {
		text = "I gotta... focus!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0269 = {
		text = "I can't, damn it!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0270 = {
		text = "Cut it out!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0271 = {
		text = "You gotta be kidding me!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0272 = {
		text = "Shit, shit, shit!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0273 = {
		text = "I'm not giving up...!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0274 = {
		text = "What can I do...?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0275 = {
		text = "You fucking rock!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0276 = {
		text = "Thanks for being there for me!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0277 = {
		text = "We're still good !",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0278 = {
		text = "Trust me!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0279 = {
		text = "I'm okay for now!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0280 = {
		text = "I'll give you the cue!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0281 = {
		text = "Let's focus!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0282 = {
		text = "Save!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0283 = {
		text = "Not load! Save!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0284 = {
		text = "Damn, that was close!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0285 = {
		text = "Thanks for the save!",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0286 = {
		text = "Anon...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0287 = {
		text = "I...",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0288 = {
		text = "Thanks to you, I'm all good.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0289 = {
		text = "You remember everything from before, yeah?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0290 = {
		text = "Yeah. I know you don't like it.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0291 = {
		text = "Is this really the same world as before?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0292 = {
		text = "Honestly, this feels weird.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0293 = {
		text = "Damn, so glad you can hear me.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0294 = {
		text = "Are you trying to cheer me up?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0295 = {
		text = "We don't need to right now.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0296 = {
		text = "Oh shit, embarrassed?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0297 = {
		text = "What?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0298 = {
		text = "Don't worry. It'll be fine.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0299 = {
		text = "Hey, settle down.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0300 = {
		text = "You nervous, too?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0301 = {
		text = "Yeah, when it's needed.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0302 = {
		text = "Almost there.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0303 = {
		text = "Yo.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0304 = {
		text = "Damn, we can't talk to each other, huh?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0305 = {
		text = "I'm counting on you.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0306 = {
		text = "Takes you back, huh?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0307 = {
		text = "I got this.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0308 = {
		text = "Don't worry.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0309 = {
		text = "It WILL go as planned.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0310 = {
		text = "Are you making fun of me?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0311 = {
		text = "I have... mixed feelings about this.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0312 = {
		text = "Doesn't feel right, does it?",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0313 = {
		text = "She's the same, but... different.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0314 = {
		text = "This is all thanks to you.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0315 = {
		text = "This... is the future we wanted back then.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_load_pol0316 = {
		text = "It's the moment we've been waiting for.",
		left = 420,
		top = 790,
		skippable = true,
	},
	ac_11_01_crs0000 = {
		text = "%CPollon, where are you now?",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_11_01_crs0001 = {
		text = "%CPollon?",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_11_01_crs0002 = {
		text = "%CPollon!",
		left = 960,
		top = 520,
		skippable = true,
	},	
	ac_05_15_dav0016 = {
		text = "%CI am blessed by Maria herself!\nI feel Our Lady's love coursing through me!",
		left = 960,
		top = 50,
		skippable = true,
	},
	ac_05_15_dav0017 = {
		text = "%CHAHAHAH! AHAHAHAHAH! HALLELUJAH!",
		left = 960,
		top = 50,
		skippable = true,
	},
	ac_05_15_dav0018 = {
		text = "%CKin of Judas, only death can cleanse your souls!",
		left = 960,
		top = 50,
		skippable = true,
	},	
	ac_02_18_asu0000 = {
		text = "%CHey, get her on the chopper!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_02_18_ozu0000 = {
		text = "%CThat's... the Vatican.",
		left = 950,
		top = 950,
		skippable = true,
	},	
	ac_02_18_pol0066 = {
		text = "%CGODDAMMIT!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_02_18_mom0047 = {
		text = "%CI'm not... wearing any... underwear...",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_02_18_pol0067 = {
		text = "%CKabukicho... Bingo.",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_02_18_pol0068 = {
		text = "%CAGHHHHH!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_01_ctr0000 = {
		text = "%CPlease respond.",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_01_crs0000 = {
		text = "%CIf this news report is credible...",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_01_plc0000 = {
		text = "%CI'm getting an error.",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_01_mom0000 = {
		text = "%CWe're connected!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_01_win0000 = {
		text = "%CThat's gotta be child's play for Cicada.",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_01_pol0001 = {
		text = "%CNo!",
		left = 950,
		top = 950,
		skippable = true,
	},
	 ac_03_01_pol0002 = {
		text = "%C...Sorry. I couldn't do it.",
		left = 950,
		top = 950,
		skippable = true,
	},
	 ac_03_01_crs0003 = {
		text = "%CPollon. We have a problem.",
		left = 950,
		top = 950,
		skippable = true,
	},
	 ac_03_01_crs0002 = {
		text = "%C...would take all day.",
		left = 950,
		top = 950,
		skippable = true,
	},
	 ac_03_01_pol0000 = {
		text = "%CHow's the channel?!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_01_ozu0001 = {
		text = "%CNow's not the time for jokes.",
		left = 950,
		top = 950,
		skippable = true,
	},
	 ac_03_01_ozu0000 = {
		text = "%CWhat's the status?",
		left = 950,
		top = 950,
		skippable = true,
	},
	 ac_03_01_crs0001 = {
		text = "%CThis is what's going on.",
		left = 950,
		top = 950,
		skippable = true,
	},
	 ac_03_01_non0000 = {
		text = "%CIt won't reach!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_05_non0012 = {
		text = "%CI gave this drone a new name! Dah dah-dah-dah! It's Beary-Airy b.2!",
		left = 960,
		top = 50,
		skippable = true,
	},
	ac_03_05_non0013 = {
		text = "%Cb.2 stands for bearsion two! Get it?",
		left = 960,
		top = 50,
		skippable = true,
	},
	ac_03_05_non0014 = {
		text = "%CSo, Polly, what do you think?!",
		left = 960,
		top = 50,
		skippable = true,
	},
	ac_03_05_non0015 = {
		text = "%CHey, are you listening? Excuse me!",
		left = 960,
		top = 50,
		skippable = true,
	},
	ac_03_20_ozu0000 = {
		text = "%CHold on tight!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_20_mom0001 = {
		text = "%CHahah... I guess I'm hungry. How about you?",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_20_pol0010 = {
		text = "%CYeah... me too.",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_20_pol0011 = {
		text = "%CFinally, I'll be able to go home—",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_20_bam0000 = {
		text = "%CTakaoka Pollon!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_20_pol0022 = {
		text = "%CCome on, Pollon, think!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_20_pol0023 = {
		text = "%CYou're not gonna stop here. This is nothing!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_20_pol0030 = {
		text = "%CSure thing. I'll pay right away.",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_20_dab0000 = {
		text = "%CWhat?",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_03_20_non0000 = {
		text = "%CFIRE!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_04_12_crs0000 = {
		text = "%CNo way...",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_04_12_kao0000 = {
		text = "%CCicada anticipated every move.",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_04_12_pol0000 = {
		text = "%CWhat the hell's going on...?",
		left = 950,
		top = 870,
		skippable = true,
	},
	ac_04_12_win0000 = {
		text = "%CThe entire world's panicking!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_04_12_cmc0000 = {
		text = "%CReporting to us live from Tokyo Station!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_04_12_swa0000 = {
		text = "%COh no... Is that in Shinjuku?",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_04_12_pol0001 = {
		text = "%CYou manipulative...",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_04_12_ozu0001 = {
		text = "%CConsider it a warning.",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_04_12_non0000 = {
		text = "%CWh-What?! No...!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_04_12_ozu0000 = {
		text = "%CHoly shit...",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_04_12_crs0001 = {
		text = "%CSimilar problems are happening elsewhere, too.",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_04_12_hac0000 = {
		text = "%CAHAHAH!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_04_12_sum0000 = {
		text = "%CLet's go help! We can't just stand here!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_05_06_bcm0000 = {
		text = "%CWh-Who do you think you are?!",
		left = 950,
		top = 870,
		skippable = true,
	},
	ac_05_06_ghm0000 = {
		text = "%CShut up, ya hypocrite!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_05_06_scm0004 = {
		text = "%CAre you fucked in the head?!",
		left = 950,
		top = 870,
		skippable = true,
	},
	ac_05_06_kbg0003 = {
		text = "%CYou're so cool, Pollon!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_05_06_gaw0000 = {
		text = "%CDon't talk like you're better than us!",
		left = 950,
		top = 870,
		skippable = true,
	},
	ac_05_06_bcm0001 = {
		text = "%CYou want your ass handed to you, punk?!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_05_22_mom0000 = {
		text = "%CPollon!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_05_22_crs0006 = {
		text = "%CI'm too late.",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_05_22_pol0025 = {
		text = "%CDamn it! It's too far away!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_05_22_ozu0000 = {
		text = "%CSomeone... Aaaghh! Anyone...!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_05_22_lim0000 = {
		text = "%CAAGHHH!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_08_19_asu0038 = {
		text = "%CYou...! You've been lying to me all this time?!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_08_19_ewn0007 = {
		text = "%C...You could say that. It's a shame, Asuma.",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_08_19_hch0001 = {
		text = "%CIn the name of God! The Third Secret of Fátima will be fulfilled!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_08_19_ozu0007 = {
		text = "%CHey! Ya gotta get outta there! The army's bombin' the place!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_08_20_pol0002 = {
		text = "%CStop right there, Okuda Ewan!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_08_20_ewn0000 = {
		text = "%C...In the name of God.",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_08_20_ozu0000 = {
		text = "%CHey! Ya gotta get outta there! The army's bombin' the place!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_08_20_fel0000 = {
		text = "%C...Hmhmm.",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_08_20_ros0000 = { 
		text = "%CThe Stigmata... Her... Sacrament... ",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_08_20_ros0001 = {
		text = "%CYou hear... the voice of God. Your consciousness... fades...",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_08_20_bek0000 = {
		text = "%CHallelujah. Hallelujah.",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_08_20_mom0000 = {
		text = "%CPollon... Pollon!",
		left = 950,
		top = 950,
		skippable = true,
	},
	ac_08_20_mom0001 = {
		text = "%CPlease! I beg of you!",
		left = 950,
		top = 950,
		skippable = true,
	},	
	ac_08_24_dav0000 = {
		text = "%CThis reunion is a blessing indeed. Mother Mary, I give you thanks.",
		left = 950,
		top = 950,
		skippable = true,
	},	
	ac_08_24_pol0023 = {
		text = "%CNNGHNNGH...!",
		left = 950,
		top = 950,
		skippable = true,
	},	
	ac_08_24_bam0000 = {
		text = "%CPollon! Run!",
		left = 950,
		top = 950,
		skippable = true,
	},	
	cfd_password_short = {
		events = [
			{
				start = 1436,
				end = 1827,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "Times are changing, swirling all around these eastern lands",
			},
			{
				start = 1827,
				end = 2027,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "Near and far, a certain jurisdiction's in our hands",
			},
			{
				start = 2027,
				end = 2209,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "Back and forth, even swirling here around our band",
			},
			{
				start = 2209,
				end = 2412,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "When your hopes and dreams crumble to dust",
			},
			{
				start = 2412,
				end = 2590,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "Give us a call—you can count on us!",
			},
			{
				start = 2590,
				end = 2797,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "And we happen to know a bit about the Six Codes",
			},
			{
				start = 2797,
				end = 3061,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "So now we dance for you in our usual salute pose!",
			},
			{
				start = 3061,
				end = 3254,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "As true heroes of justice, we hear your calls!",
			},
			{
				start = 3254,
				end = 3446,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "That's right, we're the Cyber Force Dolls!",
			},
			{
				start = 3453,
				end = 3852,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "Smiles make idols, we'll shower you in radiance",
			},
			{
				start = 3852,
				end = 4213,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "We're the real deal officers, never idle!",
			},
			{
				start = 4222,
				end = 4358,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "Any time, we'll run a trace",
			},
			{
				start = 4358,
				end = 4609,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "And for you, put baddies in their place",
			},
			{
				start = 4609,
				end = 4813,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "So don't forget: Uppercase, lowercase, symbols",
			},
			{
				start = 4813,
				end = 5005,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 25,
				text = "In my password phrase!",
			},
		],
	},	
	ac_01_05_dab0002 = {
		text = "%CSHE CAAAME!",
		left = 960,
		top = 520,
		skippable = true,
	},
	ac_01_05_dab_ex_0001 = {
		events = [
			{
				start = 0,
				end = 138,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 600,
				text = "LIVE YOUR WAY, STAY TRUE TO YOUR LOVE!",
			},
			{
				start = 138,
				end = 312,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 600,
				text = "ALWAYS KEEP IN MIND THAT YOU'RE RESPONSIBLE FOR YOUR ACTIONS!",
			},
			{
				start = 336,
				end = 438,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 600,
				text = "AND PROTECT HER AT ALL COSTS!",
			},
			{
				start = 438,
				end = 522,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 600,
				text = "BELIEVE IN WHAT YOU THINK IS RIGHT!",
			},
			{
				start = 522,
				end = 624,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 600,
				text = "DOESN'T MATTER HOW OLD YOU ARE!",
			},
			{
				start = 624,
				end = 720,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 600,
				text = "BE A MAAAN!",
			},
		],
	},	
	ac_01_05_and_ex_0001 = {
		events = [
			{
				start = 0,
				end = 63,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 680,
				text = "She showed up!",
			},
			{
				start = 63,
				end = 270,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 680,
				text = "Hahh, I was so worried you got DUMPED by her!",
			},
			{
				start = 276,
				end = 396,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 680,
				text = "But damn she's cute!",
			},
			{
				start = 396,
				end = 504,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 680,
				text = "How long have you two been together?",
			},
			{
				start = 504,
				end = 696,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 680,
				text = "Did you go on a date with her riding behind you on your Graper?",
			},
			{
				start = 738,
				end = 990,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 680,
				text = "Can you hook me up with someone, pleeease?",
			},
		],
	},	
	ac_01_05_win_ex_0001 = {
		events = [
			{
				start = 0,
				end = 222,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 760,
				text = "She's finally here! In pink! In a pink mascot costume!",
			},
			{
				start = 222,
				end = 360,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 760,
				text = "Oooh, kawaii!",
			},
			{
				start = 390,
				end = 684,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 760,
				text = "Yeah, Takaoka, I believed in you! Best wishes to you two!",
			},
			{
				start = 720,
				end = 894,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 760,
				text = "Remember, when the going gets tough, the tough get going.",
			},
			{
				start = 894,
				end = 1020,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 760,
				text = "E-mail me any time, Takaoka!",
			},
		],
	},	
	ac_08_20_slf0000 = {
		events = [
			{
				start = 20,
				end = 180,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 950,
				text = "In the name... of God...",
			},
		],
	},	
	ac_08_20_ros0002 = {
		events = [
			{
				start = 8,
				end = 210,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 870,
				text = "The Stigmata... Her... Sacrament...",
			},
		],
	},	
	ac_08_20_mom0005 = {
		events = [
			{
				start = 10,
				end = 210,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 790,
				text = "She spoke as if... she knew all things...",
			},
		],
	},	
	ac_08_20_pol0008 = {
		events = [
			{
				start = 8,
				end = 180,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 710,
				text = "Are you under the influence of the Stigmata as well?",
			},
		],
	},	
	ac_08_20_bek0001 = {
		events = [
			{
				start = 90,
				end = 210,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 630,
				text = "G-Get out, transgressor.",
			},
		],
	},	
	ac_08_20_slf0001 = {
		events = [
			{
				start = 0,
				end = 180,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 870,
				text = "In the name... of God...",
			},
		],
	},	
	ac_08_20_bka0001 = {
		events = [
			{
				start = 10,
				end = 210,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 550,
				text = "Hallelujah. Hallelujah.",
			},
		],
	},	
	ac_08_20_hch0000 = {
		events = [
			{
				start = 10,
				end = 450,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 790,
				text = "In the name of God! The Third Secret of Fátima will be fulfilled!",
			},
		],
	},	
	ac_08_20_mio0004 = {
		events = [
			{
				start = 10,
				end = 450,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 710,
				text = "I... don't want to look at you ever again.",
			},
		],
	},	
	ac_08_20_ros0003 = {
		events = [
			{
				start = 10,
				end = 390,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 630,
				text = "You hear... the voice of God. Your consciousness...",
			},
		],
	},
	ac_08_20_pol0007 = {
		events = [
			{
				start = 0,
				end = 180,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 550,
				text = "Shit! Why does it always go so wrong?!",
			},
		],
	},	
	ac_08_20_asu0004 = {
		events = [
			{
				start = 0,
				end = 180,
				hAlign = 0,
				vAlign = -1,
				absolute = false,
				x = 0,
				y = 470,
				text = "You...! You've been lying to me all this time?!",
			},
		],
	},
};
